### ISSUE TITLE
Let user configure ffmpeg parameters

### ISSUE THREAD

**Issue by kannes** [CMU-CREATE-Lab/timemachine-creator#6]
I noticed that keyframes are hardcoded to 10 and bframes to 0 (always) in https://github.com/CMU-CREATE-Lab/timemachine-creator/blob/592a17d4cecd1cf82d710bd25eeda95d489daf5c/tilestacktool/H264Encoder.cpp#L12-L17

These settings might make sense for some material but not for others. Different material might greatly benefit from certain tweaks of other parameters.

It would be great if the options passed to ffmpeg and its encoder could be modified by the user.

**Comment by rsargent** [comment]
We need to synchronize multiple video playbacks.  The tiled WebGL viewer shows several videos at once, and even though the simple HTML viewer shows a single video at a time, it requires sync when switching to a new video.  Generally when we bring in a new video tile, we need to seek quickly to bring it up to the current timebase.

seek needs to stay "cheap", which is why we overrode the GOF to 10 frames, lower than a typical video.

We disable b-frames because Chrome seeks inaccurately for videos with b-frames: https://bugs.chromium.org/p/chromium/issues/detail?id=66631
